[package]
name = "multilinear"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "0.5", features = ["asm", "std"] }
rand = { version = "0.9.0" }
rand_chacha = { version = "0.9" }
